name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Checkout the repository in the CWD
        uses: actions/checkout@v2

      - name: Install the NPM dependencies
        run: npm install

      - name: Create a blank AWS exports file
        uses: finnp/create-file-action@master
        env:
          FILE_NAME: "src/aws-exports.js"
          FILE_DATA: ""

      - name: Run the tests
        run: npm run test